/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShipsShopRouteImport } from './routes/ships-shop'
import { Route as ShipMarketRouteImport } from './routes/ship-market'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FishMarketRouteImport } from './routes/fish-market'
import { Route as DragonRouteImport } from './routes/dragon'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BossRouteImport } from './routes/boss'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as BackgroundsShopRouteImport } from './routes/backgrounds-shop'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as DragonForgeRouteImport } from './routes/dragon.forge'
import { Route as AdminSanctionsRouteImport } from './routes/admin.sanctions'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAntiCheatRouteImport } from './routes/admin.anti-cheat'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipsShopRoute = ShipsShopRouteImport.update({
  id: '/ships-shop',
  path: '/ships-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipMarketRoute = ShipMarketRouteImport.update({
  id: '/ship-market',
  path: '/ship-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FishMarketRoute = FishMarketRouteImport.update({
  id: '/fish-market',
  path: '/fish-market',
  getParentRoute: () => rootRouteImport,
} as any)
const DragonRoute = DragonRouteImport.update({
  id: '/dragon',
  path: '/dragon',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BossRoute = BossRouteImport.update({
  id: '/boss',
  path: '/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundsShopRoute = BackgroundsShopRouteImport.update({
  id: '/backgrounds-shop',
  path: '/backgrounds-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DragonForgeRoute = DragonForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => DragonRoute,
} as any)
const AdminSanctionsRoute = AdminSanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAntiCheatRoute = AdminAntiCheatRouteImport.update({
  id: '/anti-cheat',
  path: '/anti-cheat',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arena': typeof ArenaRoute
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/battle': typeof BattleRoute
  '/boss': typeof BossRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/cosmetics': typeof CosmeticsRoute
  '/dragon': typeof DragonRouteWithChildren
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/admin/anti-cheat': typeof AdminAntiCheatRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/sanctions': typeof AdminSanctionsRoute
  '/dragon/forge': typeof DragonForgeRoute
  '/p/$id': typeof PIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/battle': typeof BattleRoute
  '/boss': typeof BossRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/cosmetics': typeof CosmeticsRoute
  '/dragon': typeof DragonRouteWithChildren
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/admin/anti-cheat': typeof AdminAntiCheatRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/sanctions': typeof AdminSanctionsRoute
  '/dragon/forge': typeof DragonForgeRoute
  '/p/$id': typeof PIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arena': typeof ArenaRoute
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/battle': typeof BattleRoute
  '/boss': typeof BossRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/cosmetics': typeof CosmeticsRoute
  '/dragon': typeof DragonRouteWithChildren
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/admin/anti-cheat': typeof AdminAntiCheatRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/sanctions': typeof AdminSanctionsRoute
  '/dragon/forge': typeof DragonForgeRoute
  '/p/$id': typeof PIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/backgrounds-shop'
    | '/battle'
    | '/boss'
    | '/chat'
    | '/competitions'
    | '/cosmetics'
    | '/dragon'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/login'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/recharge'
    | '/refund'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/vip'
    | '/admin/anti-cheat'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/codes'
    | '/admin/community'
    | '/admin/competitions'
    | '/admin/content'
    | '/admin/players'
    | '/admin/sanctions'
    | '/dragon/forge'
    | '/p/$id'
    | '/players/$playerId'
    | '/u/$username'
    | '/admin/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/backgrounds-shop'
    | '/battle'
    | '/boss'
    | '/chat'
    | '/competitions'
    | '/cosmetics'
    | '/dragon'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/login'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/recharge'
    | '/refund'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/vip'
    | '/admin/anti-cheat'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/codes'
    | '/admin/community'
    | '/admin/competitions'
    | '/admin/content'
    | '/admin/players'
    | '/admin/sanctions'
    | '/dragon/forge'
    | '/p/$id'
    | '/players/$playerId'
    | '/u/$username'
    | '/admin'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/backgrounds-shop'
    | '/battle'
    | '/boss'
    | '/chat'
    | '/competitions'
    | '/cosmetics'
    | '/dragon'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/login'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/recharge'
    | '/refund'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/vip'
    | '/admin/anti-cheat'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/codes'
    | '/admin/community'
    | '/admin/competitions'
    | '/admin/content'
    | '/admin/players'
    | '/admin/sanctions'
    | '/dragon/forge'
    | '/p/$id'
    | '/players/$playerId'
    | '/u/$username'
    | '/admin/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArenaRoute: typeof ArenaRoute
  BackgroundsShopRoute: typeof BackgroundsShopRoute
  BattleRoute: typeof BattleRoute
  BossRoute: typeof BossRoute
  ChatRoute: typeof ChatRoute
  CompetitionsRoute: typeof CompetitionsRoute
  CosmeticsRoute: typeof CosmeticsRoute
  DragonRoute: typeof DragonRouteWithChildren
  FishMarketRoute: typeof FishMarketRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RechargeRoute: typeof RechargeRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShipMarketRoute: typeof ShipMarketRoute
  ShipsShopRoute: typeof ShipsShopRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VipRoute: typeof VipRoute
  PIdRoute: typeof PIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ships-shop': {
      id: '/ships-shop'
      path: '/ships-shop'
      fullPath: '/ships-shop'
      preLoaderRoute: typeof ShipsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship-market': {
      id: '/ship-market'
      path: '/ship-market'
      fullPath: '/ship-market'
      preLoaderRoute: typeof ShipMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish-market': {
      id: '/fish-market'
      path: '/fish-market'
      fullPath: '/fish-market'
      preLoaderRoute: typeof FishMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dragon': {
      id: '/dragon'
      path: '/dragon'
      fullPath: '/dragon'
      preLoaderRoute: typeof DragonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss': {
      id: '/boss'
      path: '/boss'
      fullPath: '/boss'
      preLoaderRoute: typeof BossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgrounds-shop': {
      id: '/backgrounds-shop'
      path: '/backgrounds-shop'
      fullPath: '/backgrounds-shop'
      preLoaderRoute: typeof BackgroundsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dragon/forge': {
      id: '/dragon/forge'
      path: '/forge'
      fullPath: '/dragon/forge'
      preLoaderRoute: typeof DragonForgeRouteImport
      parentRoute: typeof DragonRoute
    }
    '/admin/sanctions': {
      id: '/admin/sanctions'
      path: '/sanctions'
      fullPath: '/admin/sanctions'
      preLoaderRoute: typeof AdminSanctionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anti-cheat': {
      id: '/admin/anti-cheat'
      path: '/anti-cheat'
      fullPath: '/admin/anti-cheat'
      preLoaderRoute: typeof AdminAntiCheatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAntiCheatRoute: typeof AdminAntiCheatRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminSanctionsRoute: typeof AdminSanctionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAntiCheatRoute: AdminAntiCheatRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminSanctionsRoute: AdminSanctionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DragonRouteChildren {
  DragonForgeRoute: typeof DragonForgeRoute
}

const DragonRouteChildren: DragonRouteChildren = {
  DragonForgeRoute: DragonForgeRoute,
}

const DragonRouteWithChildren =
  DragonRoute._addFileChildren(DragonRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArenaRoute: ArenaRoute,
  BackgroundsShopRoute: BackgroundsShopRoute,
  BattleRoute: BattleRoute,
  BossRoute: BossRoute,
  ChatRoute: ChatRoute,
  CompetitionsRoute: CompetitionsRoute,
  CosmeticsRoute: CosmeticsRoute,
  DragonRoute: DragonRouteWithChildren,
  FishMarketRoute: FishMarketRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RechargeRoute: RechargeRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShipMarketRoute: ShipMarketRoute,
  ShipsShopRoute: ShipsShopRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VipRoute: VipRoute,
  PIdRoute: PIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
