/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TribeEventsRouteImport } from './routes/tribe-events'
import { Route as TribeRouteImport } from './routes/tribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShipsShopRouteImport } from './routes/ships-shop'
import { Route as ShipMarketRouteImport } from './routes/ship-market'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MyVipRouteImport } from './routes/my-vip'
import { Route as LudoRouteImport } from './routes/ludo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FishMarketRouteImport } from './routes/fish-market'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DragonRouteImport } from './routes/dragon'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BossRouteImport } from './routes/boss'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as BackgroundsShopRouteImport } from './routes/backgrounds-shop'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as GuideLegacyPlayersRouteImport } from './routes/guide.legacy-players'
import { Route as DragonForgeRouteImport } from './routes/dragon.forge'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AdminWeeklyXpRouteImport } from './routes/admin.weekly-xp'
import { Route as AdminTribeEventsRouteImport } from './routes/admin.tribe-events'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminSanctionsRouteImport } from './routes/admin.sanctions'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminPlayProductsRouteImport } from './routes/admin.play-products'
import { Route as AdminLuckyBoxRouteImport } from './routes/admin.lucky-box'
import { Route as AdminFishRouteImport } from './routes/admin.fish'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminCodesRouteImport } from './routes/admin.codes'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminArenaRouteImport } from './routes/admin.arena'
import { Route as AdminAntiCheatRouteImport } from './routes/admin.anti-cheat'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksPlaySyncRouteImport } from './routes/api/public/hooks/play-sync'
import { Route as ApiPublicHooksPlayRtdnRouteImport } from './routes/api/public/hooks/play-rtdn'
import { Route as ApiPublicHooksGoldenFisherTickRouteImport } from './routes/api/public/hooks/golden-fisher-tick'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TribeEventsRoute = TribeEventsRouteImport.update({
  id: '/tribe-events',
  path: '/tribe-events',
  getParentRoute: () => rootRouteImport,
} as any)
const TribeRoute = TribeRouteImport.update({
  id: '/tribe',
  path: '/tribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipsShopRoute = ShipsShopRouteImport.update({
  id: '/ships-shop',
  path: '/ships-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipMarketRoute = ShipMarketRouteImport.update({
  id: '/ship-market',
  path: '/ship-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MyVipRoute = MyVipRouteImport.update({
  id: '/my-vip',
  path: '/my-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const LudoRoute = LudoRouteImport.update({
  id: '/ludo',
  path: '/ludo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FishMarketRoute = FishMarketRouteImport.update({
  id: '/fish-market',
  path: '/fish-market',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DragonRoute = DragonRouteImport.update({
  id: '/dragon',
  path: '/dragon',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BossRoute = BossRouteImport.update({
  id: '/boss',
  path: '/boss',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundsShopRoute = BackgroundsShopRouteImport.update({
  id: '/backgrounds-shop',
  path: '/backgrounds-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideLegacyPlayersRoute = GuideLegacyPlayersRouteImport.update({
  id: '/guide/legacy-players',
  path: '/guide/legacy-players',
  getParentRoute: () => rootRouteImport,
} as any)
const DragonForgeRoute = DragonForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => DragonRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWeeklyXpRoute = AdminWeeklyXpRouteImport.update({
  id: '/weekly-xp',
  path: '/weekly-xp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTribeEventsRoute = AdminTribeEventsRouteImport.update({
  id: '/tribe-events',
  path: '/tribe-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSanctionsRoute = AdminSanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayProductsRoute = AdminPlayProductsRouteImport.update({
  id: '/play-products',
  path: '/play-products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLuckyBoxRoute = AdminLuckyBoxRouteImport.update({
  id: '/lucky-box',
  path: '/lucky-box',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFishRoute = AdminFishRouteImport.update({
  id: '/fish',
  path: '/fish',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArenaRoute = AdminArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAntiCheatRoute = AdminAntiCheatRouteImport.update({
  id: '/anti-cheat',
  path: '/anti-cheat',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPlaySyncRoute = ApiPublicHooksPlaySyncRouteImport.update({
  id: '/api/public/hooks/play-sync',
  path: '/api/public/hooks/play-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPlayRtdnRoute = ApiPublicHooksPlayRtdnRouteImport.update({
  id: '/api/public/hooks/play-rtdn',
  path: '/api/public/hooks/play-rtdn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGoldenFisherTickRoute =
  ApiPublicHooksGoldenFisherTickRouteImport.update({
    id: '/api/public/hooks/golden-fisher-tick',
    path: '/api/public/hooks/golden-fisher-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arena': typeof ArenaRoute
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/battle': typeof BattleRoute
  '/boss': typeof BossRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/cosmetics': typeof CosmeticsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dragon': typeof DragonRouteWithChildren
  '/faq': typeof FaqRoute
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/ludo': typeof LudoRoute
  '/my-vip': typeof MyVipRoute
  '/news': typeof NewsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/recharge': typeof RechargeRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tribe': typeof TribeRoute
  '/tribe-events': typeof TribeEventsRoute
  '/updates': typeof UpdatesRoute
  '/vip': typeof VipRoute
  '/admin/anti-cheat': typeof AdminAntiCheatRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/fish': typeof AdminFishRoute
  '/admin/lucky-box': typeof AdminLuckyBoxRoute
  '/admin/play-products': typeof AdminPlayProductsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sanctions': typeof AdminSanctionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tribe-events': typeof AdminTribeEventsRoute
  '/admin/weekly-xp': typeof AdminWeeklyXpRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dragon/forge': typeof DragonForgeRoute
  '/guide/legacy-players': typeof GuideLegacyPlayersRoute
  '/p/$id': typeof PIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/golden-fisher-tick': typeof ApiPublicHooksGoldenFisherTickRoute
  '/api/public/hooks/play-rtdn': typeof ApiPublicHooksPlayRtdnRoute
  '/api/public/hooks/play-sync': typeof ApiPublicHooksPlaySyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/battle': typeof BattleRoute
  '/boss': typeof BossRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/cosmetics': typeof CosmeticsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dragon': typeof DragonRouteWithChildren
  '/faq': typeof FaqRoute
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/ludo': typeof LudoRoute
  '/my-vip': typeof MyVipRoute
  '/news': typeof NewsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/recharge': typeof RechargeRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tribe': typeof TribeRoute
  '/tribe-events': typeof TribeEventsRoute
  '/updates': typeof UpdatesRoute
  '/vip': typeof VipRoute
  '/admin/anti-cheat': typeof AdminAntiCheatRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/fish': typeof AdminFishRoute
  '/admin/lucky-box': typeof AdminLuckyBoxRoute
  '/admin/play-products': typeof AdminPlayProductsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sanctions': typeof AdminSanctionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tribe-events': typeof AdminTribeEventsRoute
  '/admin/weekly-xp': typeof AdminWeeklyXpRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dragon/forge': typeof DragonForgeRoute
  '/guide/legacy-players': typeof GuideLegacyPlayersRoute
  '/p/$id': typeof PIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/golden-fisher-tick': typeof ApiPublicHooksGoldenFisherTickRoute
  '/api/public/hooks/play-rtdn': typeof ApiPublicHooksPlayRtdnRoute
  '/api/public/hooks/play-sync': typeof ApiPublicHooksPlaySyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/arena': typeof ArenaRoute
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/battle': typeof BattleRoute
  '/boss': typeof BossRoute
  '/chat': typeof ChatRoute
  '/competitions': typeof CompetitionsRoute
  '/cosmetics': typeof CosmeticsRoute
  '/delete-account': typeof DeleteAccountRoute
  '/dragon': typeof DragonRouteWithChildren
  '/faq': typeof FaqRoute
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/ludo': typeof LudoRoute
  '/my-vip': typeof MyVipRoute
  '/news': typeof NewsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/recharge': typeof RechargeRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tribe': typeof TribeRoute
  '/tribe-events': typeof TribeEventsRoute
  '/updates': typeof UpdatesRoute
  '/vip': typeof VipRoute
  '/admin/anti-cheat': typeof AdminAntiCheatRoute
  '/admin/arena': typeof AdminArenaRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/fish': typeof AdminFishRoute
  '/admin/lucky-box': typeof AdminLuckyBoxRoute
  '/admin/play-products': typeof AdminPlayProductsRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sanctions': typeof AdminSanctionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tribe-events': typeof AdminTribeEventsRoute
  '/admin/weekly-xp': typeof AdminWeeklyXpRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/dragon/forge': typeof DragonForgeRoute
  '/guide/legacy-players': typeof GuideLegacyPlayersRoute
  '/p/$id': typeof PIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/golden-fisher-tick': typeof ApiPublicHooksGoldenFisherTickRoute
  '/api/public/hooks/play-rtdn': typeof ApiPublicHooksPlayRtdnRoute
  '/api/public/hooks/play-sync': typeof ApiPublicHooksPlaySyncRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/backgrounds-shop'
    | '/battle'
    | '/boss'
    | '/chat'
    | '/competitions'
    | '/cosmetics'
    | '/delete-account'
    | '/dragon'
    | '/faq'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/invite'
    | '/login'
    | '/ludo'
    | '/my-vip'
    | '/news'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/quests'
    | '/recharge'
    | '/refund'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/tribe'
    | '/tribe-events'
    | '/updates'
    | '/vip'
    | '/admin/anti-cheat'
    | '/admin/arena'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/codes'
    | '/admin/community'
    | '/admin/competitions'
    | '/admin/content'
    | '/admin/fish'
    | '/admin/lucky-box'
    | '/admin/play-products'
    | '/admin/players'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/sanctions'
    | '/admin/tickets'
    | '/admin/tribe-events'
    | '/admin/weekly-xp'
    | '/auth/confirm'
    | '/dragon/forge'
    | '/guide/legacy-players'
    | '/p/$id'
    | '/players/$playerId'
    | '/u/$username'
    | '/admin/'
    | '/api/public/hooks/golden-fisher-tick'
    | '/api/public/hooks/play-rtdn'
    | '/api/public/hooks/play-sync'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/backgrounds-shop'
    | '/battle'
    | '/boss'
    | '/chat'
    | '/competitions'
    | '/cosmetics'
    | '/delete-account'
    | '/dragon'
    | '/faq'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/invite'
    | '/login'
    | '/ludo'
    | '/my-vip'
    | '/news'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/quests'
    | '/recharge'
    | '/refund'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/tribe'
    | '/tribe-events'
    | '/updates'
    | '/vip'
    | '/admin/anti-cheat'
    | '/admin/arena'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/codes'
    | '/admin/community'
    | '/admin/competitions'
    | '/admin/content'
    | '/admin/fish'
    | '/admin/lucky-box'
    | '/admin/play-products'
    | '/admin/players'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/sanctions'
    | '/admin/tickets'
    | '/admin/tribe-events'
    | '/admin/weekly-xp'
    | '/auth/confirm'
    | '/dragon/forge'
    | '/guide/legacy-players'
    | '/p/$id'
    | '/players/$playerId'
    | '/u/$username'
    | '/admin'
    | '/api/public/hooks/golden-fisher-tick'
    | '/api/public/hooks/play-rtdn'
    | '/api/public/hooks/play-sync'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/backgrounds-shop'
    | '/battle'
    | '/boss'
    | '/chat'
    | '/competitions'
    | '/cosmetics'
    | '/delete-account'
    | '/dragon'
    | '/faq'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/invite'
    | '/login'
    | '/ludo'
    | '/my-vip'
    | '/news'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/quests'
    | '/recharge'
    | '/refund'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/tribe'
    | '/tribe-events'
    | '/updates'
    | '/vip'
    | '/admin/anti-cheat'
    | '/admin/arena'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/codes'
    | '/admin/community'
    | '/admin/competitions'
    | '/admin/content'
    | '/admin/fish'
    | '/admin/lucky-box'
    | '/admin/play-products'
    | '/admin/players'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/sanctions'
    | '/admin/tickets'
    | '/admin/tribe-events'
    | '/admin/weekly-xp'
    | '/auth/confirm'
    | '/dragon/forge'
    | '/guide/legacy-players'
    | '/p/$id'
    | '/players/$playerId'
    | '/u/$username'
    | '/admin/'
    | '/api/public/hooks/golden-fisher-tick'
    | '/api/public/hooks/play-rtdn'
    | '/api/public/hooks/play-sync'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArenaRoute: typeof ArenaRoute
  BackgroundsShopRoute: typeof BackgroundsShopRoute
  BattleRoute: typeof BattleRoute
  BossRoute: typeof BossRoute
  ChatRoute: typeof ChatRoute
  CompetitionsRoute: typeof CompetitionsRoute
  CosmeticsRoute: typeof CosmeticsRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  DragonRoute: typeof DragonRouteWithChildren
  FaqRoute: typeof FaqRoute
  FishMarketRoute: typeof FishMarketRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  InventoryRoute: typeof InventoryRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  LudoRoute: typeof LudoRoute
  MyVipRoute: typeof MyVipRoute
  NewsRoute: typeof NewsRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  QuestsRoute: typeof QuestsRoute
  RechargeRoute: typeof RechargeRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShipMarketRoute: typeof ShipMarketRoute
  ShipsShopRoute: typeof ShipsShopRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TribeRoute: typeof TribeRoute
  TribeEventsRoute: typeof TribeEventsRoute
  UpdatesRoute: typeof UpdatesRoute
  VipRoute: typeof VipRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  GuideLegacyPlayersRoute: typeof GuideLegacyPlayersRoute
  PIdRoute: typeof PIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicHooksGoldenFisherTickRoute: typeof ApiPublicHooksGoldenFisherTickRoute
  ApiPublicHooksPlayRtdnRoute: typeof ApiPublicHooksPlayRtdnRoute
  ApiPublicHooksPlaySyncRoute: typeof ApiPublicHooksPlaySyncRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribe-events': {
      id: '/tribe-events'
      path: '/tribe-events'
      fullPath: '/tribe-events'
      preLoaderRoute: typeof TribeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribe': {
      id: '/tribe'
      path: '/tribe'
      fullPath: '/tribe'
      preLoaderRoute: typeof TribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ships-shop': {
      id: '/ships-shop'
      path: '/ships-shop'
      fullPath: '/ships-shop'
      preLoaderRoute: typeof ShipsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship-market': {
      id: '/ship-market'
      path: '/ship-market'
      fullPath: '/ship-market'
      preLoaderRoute: typeof ShipMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-vip': {
      id: '/my-vip'
      path: '/my-vip'
      fullPath: '/my-vip'
      preLoaderRoute: typeof MyVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ludo': {
      id: '/ludo'
      path: '/ludo'
      fullPath: '/ludo'
      preLoaderRoute: typeof LudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish-market': {
      id: '/fish-market'
      path: '/fish-market'
      fullPath: '/fish-market'
      preLoaderRoute: typeof FishMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dragon': {
      id: '/dragon'
      path: '/dragon'
      fullPath: '/dragon'
      preLoaderRoute: typeof DragonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boss': {
      id: '/boss'
      path: '/boss'
      fullPath: '/boss'
      preLoaderRoute: typeof BossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgrounds-shop': {
      id: '/backgrounds-shop'
      path: '/backgrounds-shop'
      fullPath: '/backgrounds-shop'
      preLoaderRoute: typeof BackgroundsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/legacy-players': {
      id: '/guide/legacy-players'
      path: '/guide/legacy-players'
      fullPath: '/guide/legacy-players'
      preLoaderRoute: typeof GuideLegacyPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dragon/forge': {
      id: '/dragon/forge'
      path: '/forge'
      fullPath: '/dragon/forge'
      preLoaderRoute: typeof DragonForgeRouteImport
      parentRoute: typeof DragonRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/weekly-xp': {
      id: '/admin/weekly-xp'
      path: '/weekly-xp'
      fullPath: '/admin/weekly-xp'
      preLoaderRoute: typeof AdminWeeklyXpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tribe-events': {
      id: '/admin/tribe-events'
      path: '/tribe-events'
      fullPath: '/admin/tribe-events'
      preLoaderRoute: typeof AdminTribeEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sanctions': {
      id: '/admin/sanctions'
      path: '/sanctions'
      fullPath: '/admin/sanctions'
      preLoaderRoute: typeof AdminSanctionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/play-products': {
      id: '/admin/play-products'
      path: '/play-products'
      fullPath: '/admin/play-products'
      preLoaderRoute: typeof AdminPlayProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lucky-box': {
      id: '/admin/lucky-box'
      path: '/lucky-box'
      fullPath: '/admin/lucky-box'
      preLoaderRoute: typeof AdminLuckyBoxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fish': {
      id: '/admin/fish'
      path: '/fish'
      fullPath: '/admin/fish'
      preLoaderRoute: typeof AdminFishRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arena': {
      id: '/admin/arena'
      path: '/arena'
      fullPath: '/admin/arena'
      preLoaderRoute: typeof AdminArenaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anti-cheat': {
      id: '/admin/anti-cheat'
      path: '/anti-cheat'
      fullPath: '/admin/anti-cheat'
      preLoaderRoute: typeof AdminAntiCheatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/play-sync': {
      id: '/api/public/hooks/play-sync'
      path: '/api/public/hooks/play-sync'
      fullPath: '/api/public/hooks/play-sync'
      preLoaderRoute: typeof ApiPublicHooksPlaySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/play-rtdn': {
      id: '/api/public/hooks/play-rtdn'
      path: '/api/public/hooks/play-rtdn'
      fullPath: '/api/public/hooks/play-rtdn'
      preLoaderRoute: typeof ApiPublicHooksPlayRtdnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/golden-fisher-tick': {
      id: '/api/public/hooks/golden-fisher-tick'
      path: '/api/public/hooks/golden-fisher-tick'
      fullPath: '/api/public/hooks/golden-fisher-tick'
      preLoaderRoute: typeof ApiPublicHooksGoldenFisherTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAntiCheatRoute: typeof AdminAntiCheatRoute
  AdminArenaRoute: typeof AdminArenaRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminFishRoute: typeof AdminFishRoute
  AdminLuckyBoxRoute: typeof AdminLuckyBoxRoute
  AdminPlayProductsRoute: typeof AdminPlayProductsRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSanctionsRoute: typeof AdminSanctionsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminTribeEventsRoute: typeof AdminTribeEventsRoute
  AdminWeeklyXpRoute: typeof AdminWeeklyXpRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAntiCheatRoute: AdminAntiCheatRoute,
  AdminArenaRoute: AdminArenaRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminFishRoute: AdminFishRoute,
  AdminLuckyBoxRoute: AdminLuckyBoxRoute,
  AdminPlayProductsRoute: AdminPlayProductsRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSanctionsRoute: AdminSanctionsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminTribeEventsRoute: AdminTribeEventsRoute,
  AdminWeeklyXpRoute: AdminWeeklyXpRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DragonRouteChildren {
  DragonForgeRoute: typeof DragonForgeRoute
}

const DragonRouteChildren: DragonRouteChildren = {
  DragonForgeRoute: DragonForgeRoute,
}

const DragonRouteWithChildren =
  DragonRoute._addFileChildren(DragonRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArenaRoute: ArenaRoute,
  BackgroundsShopRoute: BackgroundsShopRoute,
  BattleRoute: BattleRoute,
  BossRoute: BossRoute,
  ChatRoute: ChatRoute,
  CompetitionsRoute: CompetitionsRoute,
  CosmeticsRoute: CosmeticsRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  DragonRoute: DragonRouteWithChildren,
  FaqRoute: FaqRoute,
  FishMarketRoute: FishMarketRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  InventoryRoute: InventoryRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  LudoRoute: LudoRoute,
  MyVipRoute: MyVipRoute,
  NewsRoute: NewsRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  QuestsRoute: QuestsRoute,
  RechargeRoute: RechargeRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShipMarketRoute: ShipMarketRoute,
  ShipsShopRoute: ShipsShopRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TribeRoute: TribeRoute,
  TribeEventsRoute: TribeEventsRoute,
  UpdatesRoute: UpdatesRoute,
  VipRoute: VipRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  GuideLegacyPlayersRoute: GuideLegacyPlayersRoute,
  PIdRoute: PIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicHooksGoldenFisherTickRoute: ApiPublicHooksGoldenFisherTickRoute,
  ApiPublicHooksPlayRtdnRoute: ApiPublicHooksPlayRtdnRoute,
  ApiPublicHooksPlaySyncRoute: ApiPublicHooksPlaySyncRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
