/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShipsShopRouteImport } from './routes/ships-shop'
import { Route as ShipMarketRouteImport } from './routes/ship-market'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FishMarketRouteImport } from './routes/fish-market'
import { Route as CosmeticsRouteImport } from './routes/cosmetics'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BackgroundsShopRouteImport } from './routes/backgrounds-shop'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipsShopRoute = ShipsShopRouteImport.update({
  id: '/ships-shop',
  path: '/ships-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipMarketRoute = ShipMarketRouteImport.update({
  id: '/ship-market',
  path: '/ship-market',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FishMarketRoute = FishMarketRouteImport.update({
  id: '/fish-market',
  path: '/fish-market',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmeticsRoute = CosmeticsRouteImport.update({
  id: '/cosmetics',
  path: '/cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundsShopRoute = BackgroundsShopRouteImport.update({
  id: '/backgrounds-shop',
  path: '/backgrounds-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/chat': typeof ChatRoute
  '/cosmetics': typeof CosmeticsRoute
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/players': typeof AdminPlayersRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/chat': typeof ChatRoute
  '/cosmetics': typeof CosmeticsRoute
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/players': typeof AdminPlayersRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/backgrounds-shop': typeof BackgroundsShopRoute
  '/chat': typeof ChatRoute
  '/cosmetics': typeof CosmeticsRoute
  '/fish-market': typeof FishMarketRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ship-market': typeof ShipMarketRoute
  '/ships-shop': typeof ShipsShopRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/players': typeof AdminPlayersRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/backgrounds-shop'
    | '/chat'
    | '/cosmetics'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/login'
    | '/profile'
    | '/recharge'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/content'
    | '/admin/players'
    | '/players/$playerId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backgrounds-shop'
    | '/chat'
    | '/cosmetics'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/login'
    | '/profile'
    | '/recharge'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/content'
    | '/admin/players'
    | '/players/$playerId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/backgrounds-shop'
    | '/chat'
    | '/cosmetics'
    | '/fish-market'
    | '/forgot-password'
    | '/friends'
    | '/inventory'
    | '/login'
    | '/profile'
    | '/recharge'
    | '/reset-password'
    | '/ship-market'
    | '/ships-shop'
    | '/shop'
    | '/signup'
    | '/admin/audit'
    | '/admin/broadcasts'
    | '/admin/content'
    | '/admin/players'
    | '/players/$playerId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BackgroundsShopRoute: typeof BackgroundsShopRoute
  ChatRoute: typeof ChatRoute
  CosmeticsRoute: typeof CosmeticsRoute
  FishMarketRoute: typeof FishMarketRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RechargeRoute: typeof RechargeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShipMarketRoute: typeof ShipMarketRoute
  ShipsShopRoute: typeof ShipsShopRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ships-shop': {
      id: '/ships-shop'
      path: '/ships-shop'
      fullPath: '/ships-shop'
      preLoaderRoute: typeof ShipsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship-market': {
      id: '/ship-market'
      path: '/ship-market'
      fullPath: '/ship-market'
      preLoaderRoute: typeof ShipMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fish-market': {
      id: '/fish-market'
      path: '/fish-market'
      fullPath: '/fish-market'
      preLoaderRoute: typeof FishMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetics': {
      id: '/cosmetics'
      path: '/cosmetics'
      fullPath: '/cosmetics'
      preLoaderRoute: typeof CosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgrounds-shop': {
      id: '/backgrounds-shop'
      path: '/backgrounds-shop'
      fullPath: '/backgrounds-shop'
      preLoaderRoute: typeof BackgroundsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BackgroundsShopRoute: BackgroundsShopRoute,
  ChatRoute: ChatRoute,
  CosmeticsRoute: CosmeticsRoute,
  FishMarketRoute: FishMarketRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RechargeRoute: RechargeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShipMarketRoute: ShipMarketRoute,
  ShipsShopRoute: ShipsShopRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
