- name: Build and Optimize Artifacts
        env:
          SIGNING_STORE_PASSWORD: "HamorGame2026"
          SIGNING_KEY_PASSWORD: "HamorGame2026"
        run: |
          cd android
          # تنظيف شامل
          ./gradlew clean
          
          # بناء الـ AAB (للمتجر)
          ./gradlew bundleRelease -x lint
          
          # بناء APK (Universal) لضمان التوافق مع كل الأجهزة
          ./gradlew assembleRelease -x lint
          
          sed -i "s/versionCode [0-9]*/versionCode ${{ github.run_number }}/" app/build.gradle

      - name: Sign & Align Artifacts
        run: |
          KEYSTORE="android/app/hamor-upload-key.keystore"
          PASSWORD="HamorGame2026"
          ALIAS="hamor-key-alias"
          
          echo "--- توقيع الملفات ---"
          
          # 1. توقيع الـ AAB (المستخدم للرفع على Google Play)
          AAB=$(find android/app/build/outputs/bundle/release/ -name "*.aab" | head -n 1)
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore $KEYSTORE -storepass $PASSWORD -keypass $PASSWORD $AAB $ALIAS || true
          mv $AAB ./hamor-play-store.aab
          
          # 2. توقيع الـ APK (المستخدم للتثبيت اليدوي)
          # نستخدم find للبحث عن أي ملف APK في مجلد الـ release
          RAW_APK=$(find android/app/build/outputs/apk/release/ -name "*.apk" | head -n 1)
          
          if [ -f "$RAW_APK" ]; then
            # التأكد من عمل zipalign للملف
            ZIPALIGN_PATH=$(find $ANDROID_HOME/build-tools/ -name zipalign | head -n 1)
            $ZIPALIGN_PATH -v 4 $RAW_APK ./hamor-aligned.apk
            
            jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore $KEYSTORE -storepass $PASSWORD -keypass $PASSWORD ./hamor-aligned.apk $ALIAS || true
            mv ./hamor-aligned.apk ./hamor-app-release.apk
          else
            echo "خطأ: لم يتم العثور على ملف APK!"
            exit 1
          fi
